### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JeffreyCA** [JeffreyCA/APOD-Gallery#1]
**Finished**
- [x] Rework setting wallpapers
- [x] Permissions
- [x] Landscape support (Tablets)
- [x] Bugfix: Description text cut-off
---
**Daily Wallpapers**
- [x] Deal with Evie Launcher crash
- [x] Decide on optimal Bitmap crop/scale algorithm
- [x] Prevent unnecessary queries if image already retrieved for current day (use `SharedPreferences` entry)
- [x] Refine SettingsActivity options for wallpapers
- [x] Create web application that writes to a Firebase database (provides latest image URL)
---
**App Widget**
- [x] Clicking widget content opens app to corresponding date
---
**Miscellaneous**
- [x] Improve first-time launch message
- [x] Dialog to enable daily wallpaper changer on first-time launch
- [x] Test on tablet devices
---
**For next release:**
- [x] Remove hyperlinks in Acknowledgements screen

Last Updated: May 21, 2017
